services:
  apitest:
    build:
      dockerfile: Dockerfile.tests
      target: apitest
    depends_on:
      - 'database'
    environment:
      - DB_username=root
      - DB_password=123
      - DB_host=database
      - DB_port=3306
      - DB_database=pedese
  database:
    image: 'mysql:8'
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=pedese
